import { TutorialProvider } from "@/components/context/TutorialContext";
import AppProviders from "@/components/providers/AppProviders";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import TutorialOverlay from "@/components/providers/TutorialOverlay";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      elements:{
        formButtonPrimary:'bg-primary hover:bg-primary/90 text-sm  !shadow-none'
      }
    }} afterSignOutUrl={'/sign-in'}>
    <html lang="en">
      <body className={inter.className}>
  
        <AppProviders>
          <TutorialProvider>
          {children}
           <TutorialOverlay />
          </TutorialProvider>
          </AppProviders>
       
        </body>
        <Toaster richColors/>
    </html>
    </ClerkProvider>
  );
}
