import { TutorialProvider } from "@/components/context/TutorialContext";
import AppProviders from "@/components/providers/AppProviders";
import TutorialOverlay from "@/components/providers/TutorialOverlay";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>
          <TutorialProvider>
            {children}
            <TutorialOverlay />
          </TutorialProvider>
        </AppProviders>
        <Toaster richColors />
      </body>
    </html>
  );
}